# Generated by Django 5.2.7 on 2025-11-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_destination_delete_destinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured_Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='featured_destinations/')),
                ('ratings', models.DecimalField(decimal_places=2, max_digits=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expeditions', models.PositiveIntegerField(default=0)),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
    ]
