# Generated by Django 5.2.7 on 2025-11-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_featured_destinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured_Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='featured_tours/')),
                ('duration', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tag', models.CharField(max_length=50)),
                ('destinations', models.CharField(max_length=200)),
            ],
        ),
    ]
