# Generated by Django 5.2.7 on 2025-11-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_featured_tours'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured_tours',
            name='group_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='featured_tours',
            name='ratings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
