# Generated by Django 5.2.7 on 2025-11-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_featured_tours_group_size_featured_tours_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured_tours',
            name='destinations',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
