# Generated by Django 5.2.2 on 2025-11-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_featured_tours_destinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='testimonials/')),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
