# Generated by Django 5.2.2 on 2025-11-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tours/')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in days')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('ratings', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('group_size', models.PositiveIntegerField(default=0)),
                ('destinations', models.ManyToManyField(blank=True, related_name='tours', to='book.destination')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
            },
        ),
    ]
